name: Proxmox Zero Trust CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-infrastructure:
    runs-on: self-hosted

    env:
      RUNNER_ALLOW_RUNASROOT: 1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: ./proxmox-iac
        run: terraform init

      - name: Terraform Apply
        working-directory: ./proxmox-iac
        # Chạy Terraform đẻ/cập nhật 8 máy ảo
        run: terraform apply -auto-approve

      # Giai đoạn Ansible sẽ được bổ sung vào đây sau khi chúng ta viết xong Playbook cho Tunnels
